# Generated by Django 3.0.2 on 2020-01-11 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('status', models.CharField(blank=True, choices=[('student', 'Student'), ('private', 'Private Sector'), ('government', 'Government Sector'), ('freelance', 'Freelance'), ('unemployed', 'Unemployed')], max_length=50, null=True, verbose_name='Profession Status')),
                ('highest_qualification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Highest Qualification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='candidate_user')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
